### ISSUE TITLE
Lost Messages When Communicating with Other XMPP Apps

### ISSUE THREAD

**Issue by a11fruitless** [ChatSecure/ChatSecure-iOS#339] opened 2015-04-20 02:29 UTC
Running a closed XMPP server using the most recent version of Prosody. Clients typically connect through ChatSecure, Pidgin, and Psi+. When users updated to the latest version of ChatSecure (3.0), we started having an issue. 

Communication between ChatSecure apps appears to be working fine. However, when a ChatSecure app communicates with either Pidgin or Psi+, messages start to be lost. After the ChatSecure user sends a message and it is replied to, all further messages from the ChatSecure user are lost. Typing notifications are still received, but the messages do not appear. Messages from Pidgin or Psi+ are still appearing in ChatSecure though. When using OTR encryption, the problem is resolved and ChatSecure works as it should. Users who revert back to the previous version of ChatSecure (2.x) do not experience any issue. Also, communication between Pidgin and Psi+ users is all behaving normally.

I would love to know if anyone else if having an issue like this. My Prosody server is pretty standard and essentially uses the basic modules.

**Comment by chrisballinger** [comment] 2015-04-23 16:41
Perhaps try turning off opportunistic encryption ("auto-start encryption") in ChatSecure?

**Comment by a11fruitless** [comment] 2015-04-24 01:27
Thank you for the response! Unfortunately, all the clients have opportunistic OTR encryption turned off already. It was causing issues with lost messages when people were switching between devices (iPad to iPhone to desktops, etc.). We typically only enable OTR when we are passing sensitive information. 

I have been watching for this issue ever since ChatSecure 3.0 was released, and I am surprised I have not seen it reported yet. I guess it is not that common to run your own XMPP server. My first inclination would be to assume it is something wrong with my server configuration, but since users are able to revert back to ChatSecure 2.x to resolve the issue, I am less likely to believe it is that.

**Comment by chrisballinger** [comment] 2015-04-24 17:58
Please email me directly with an account on your server to test against. Thanks!

**Comment by chrisballinger** [comment] 2015-04-29 21:04
@a11fruitless We've identified the issue and it will be fixed in the v3.1 release. Part of the issue is that opportunistic encryption was on regardless of the setting, and that libotr was giving us empty messages after it realized the other side didn't support encryption.

**Comment by a11fruitless** [comment] 2015-04-30 06:28
Great! Glad to hear this since we use ChatSecure so heavily. Thanks for a great app.

**Comment by chrisballinger** [comment] 2015-05-01 18:47
:+1:

**Closed by chrisballinger** 2015-05-01 18:47 UTC
