### ISSUE TITLE
Push notifications with mod_cloud_notify not working

### ISSUE THREAD

**Issue by remko** [ChatSecure/ChatSecure-iOS#712] opened 2017-03-05 20:27 UTC
I'm trying out ChatSecure for the first time against a recent development version of Prosody with `mod_cloud_notify`, and it seems push notifications aren't working.

When tracing the XML on the server, I noticed the following:

    RECV <iq type="set"><enable xmlns="urn:xmpp:push:0" jid="pubsub.chatsecure.org" [...]
    [...]
    SEND <iq type='error'><error type='modify'><bad-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
            <text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Missing required &apos;id&apos; attribute</text>
      </error></iq>

Could it be that ChatSecure is not providing `id`s on its `enable` call? I'm not sure if it is new for Prosody to barf on this, but `id`s on IQs are required per 6120.

*Update:* It *is* new for Prosody to barf on this.

**Comment by chrisballinger** [comment] 2017-03-05 20:49
This is fixed in master branch, should be putting out a beta this week

**Comment by tmolitor-stud-tu** [comment] 2017-03-07 22:09
@chrisballinger how can I get those betas?

**Comment by tmolitor-stud-tu** [comment] 2017-03-07 22:24
@chrisballinger I'm using version 4.0.3 and chatsecure isn't even trying to enable push (confirmed by reading the server logs on my prosody 0.10 server having mod_cloud_notify).
Conversations activates push on this server just fine and I even confirmed that push is actually working as it should.

Half a year ago I used Chatsecure 3.x (don't remember the exact version numer) and it registered for push just fine (but had other issues so I couldn't use it)

**Comment by chrisballinger** [comment] 2017-03-07 22:34
@tmolitor-stud-tu There are issues reported with Prosody 0.10, but I'm not sure the cause. Someone else was able to fix the issue by downgrading to Prosody 0.9.x.

**Comment by tmolitor-stud-tu** [comment] 2017-03-07 22:37
@chrisballinger I rewrote most of the push module for prosody (will be released to the community modules repo in a couple of days), but I don't see any push related activity in the logs.
Prosody announces the push capability and nothing more happens.

If you want, you can contact me at tmolitor@datenknoten.me (xmpp) to discuss this issue further. I currently have an iOS 10 device at hand to test :)

**Comment by tmolitor-stud-tu** [comment] 2017-03-07 22:40
@chrisballinger This is the capabilities iq:
`@chrisballinger This is the capabilities iq:
`<iq id='33EF21E2-61C5-4B4F-922F-C67A6B4AA3B1' type='result' to='user@example.org/chatsecure66017' from='user@example.org'><query xmlns='http://jabber.org/protocol/disco#info'><feature var='urn:xmpp:push:0'/><identity type='pep' category='pubsub'/><feature var='http://jabber.org/protocol/pubsub#publish'/><feature var='urn:xmpp:mam:0'/><feature var='urn:xmpp:mam:1'/><feature var='urn:xmpp:mam:2'/><feature var='urn:xmpp:sid:0'/></query></iq>``

**Comment by tmolitor-stud-tu** [comment] 2017-03-07 22:45
@chrisballinger Sorry, my fault. In my latest test it didn't try to enable push, but in one of my first tests it tried it without specifying an id in the iq stanza. Thus this seems to be related to exactly this issue ;)

**Comment by chrisballinger** [comment] 2017-03-09 01:00
@remko 4.0.4 (68) beta is out which should fix this issue. Email me if you want to sign up for the TestFlight builds.

**Comment by chrisballinger** [comment] 2017-03-22 18:04
4.0.4 is now available on the App Store

**Closed by chrisballinger** 2017-03-22 18:04 UTC
