### ISSUE TITLE
Beta 58 UI hangs often

### ISSUE THREAD

**Issue by ge0rg** [ChatSecure/ChatSecure-iOS#640] opened 2017-01-04 09:16 UTC
After updating to beta 58 I notice that ChatSecure sometimes locks up and does not react to UI interactions any more. It takes longer than 10 seconds to recover, and it seems not to crash.

After waiting for a while it continues working, there is no indication of the deadlock detector / crashes.

**Comment by chrisballinger** [comment] 2017-01-05 00:09
Dupe of #552

**Closed by chrisballinger** 2017-01-05 00:09 UTC
Labels: Bug, UI / UX
