### ISSUE TITLE
[Feature Request] Encrypted Group Chat

### ISSUE THREAD

**Issue by Pentabyteman** [ChatSecure/ChatSecure-iOS#835] opened 2017-08-11 09:14 UTC
So far, when sending messages on group chats like name@conversations.jabber.de, there are no encryption options whatsoever. It would be great if either a multi-party OTR encryption or an openPGP encryption could be supported in future releases.

**Comment by mimi89999** [comment] 2017-08-20 20:51
Duplicate of #580 . Please close.

**Closed** 2017-08-20 21:09 UTC
