### ISSUE TITLE
XEP-0333 implementation

### ISSUE THREAD

**Issue by hemee** [ChatSecure/ChatSecure-iOS#798] opened 2017-06-24 06:29 UTC
Since ChatSecure becomes more user-friendly (sometimes), it would be nice to see that your message is actually read. The XEP may mimic as it's easy to do, but I'm pretty sure it's not. Afaik, XEP-0030 is already there, so minus one headache. That is what XEP expects from a client:

Enable a client to mark a message as markable.
Enable a client to mark the last received message in a chat.
Enable a client to mark the last displayed message in a chat.
Enable a client to mark the last acknowledged message in a chat.
Enable a client to fetch and set Chat Markers regardless of wether the other users in a chat are online.

Furthermore, I'd outline that it's important to implement a switch to enable/disable acknowledgements, since user may wish not to send marks.

**Comment by chrisballinger** [comment] 2017-06-24 17:29
Thanks for the reminder! Definitely something I want as well, just haven't done it yet. Dupe of #512

**Closed by chrisballinger** 2017-06-24 17:29 UTC
