### ISSUE TITLE
Duplicated muc

### ISSUE THREAD

**Issue by lucazulian** [ChatSecure/ChatSecure-iOS#507] opened 2016-06-05 17:02 UTC
When I create multiple MUC, the first two mucs work correctly, but "sometimes" it duplicates the room.
It seems that the client shows the MUC as a private chat and then, when I type something, it shows the MUC chat.

![untitled](https://cloud.githubusercontent.com/assets/3492584/15806931/a2c77e32-2b4f-11e6-8032-e978601d7633.png)

**Comment by chrisballinger** [comment] 2016-06-06 20:22
Oh interesting. Do you know the server software?

**Comment by lucazulian** [comment] 2016-06-06 20:42
Ejabber...if you want I can give you the docker compose file. But I suspect that the problem cold be the carbon copy module

**Comment by theSouL** [comment] 2016-08-16 09:53
I can't provide screenshots nor logs but I can confirm that happens with Prosody too.
Two conferences are created when someone invites you.
One with the subject and another with the MUC address.
The conference that works is the one showing the subject.
 The other MUC, is just like a mirror of the working MUC without people, and messages the user write inside that MUC are not sent.

**Comment by dhomes** [comment] 2016-10-03 00:06
same here, i modified the OTRXMPPManager so that no history is requested : 
        
[historyElement addAttributeWithName:@"since" stringValue:dateTimeString]  

[historyElement addAttributeWithName:@"maxstanzas" stringValue:@"0"];

and then also fully removing it, none works

Seems to me that the databaseRoomKey is computed differently and thus creates a new room on 

- (NSString *)joinRoom:(XMPPJID *)jid withNickname:(NSString *)name subject:(NSString *)subject

Any ideas here?

**Comment by dhomes** [comment] 2016-10-03 14:18
seems to be an issue here?

/**
 * Stores or otherwise handles the given message element.
 **/
- (void)handleIncomingMessage:(XMPPMessage *)message room:(XMPPRoom *)room {
    XMPPJID *myRoomJID = room.myRoomJID;
    XMPPJID *messageJID = [message from];
    
    NSLog(@"myRoomJid: %@  messageJid: %@",myRoomJID.bare,messageJID.bare);
    if ([myRoomJID isEqualToJID:messageJID])
    {
        if (![message wasDelayed])
        {
            // Ignore - we already stored message in handleOutgoingMessage:room:
            return;
        }
    }
    
    [self.databaseConnection asyncReadWithBlock:^(YapDatabaseReadTransaction * _Nonnull transaction) {
        [transaction objectForKey:messageJID.bare inCollection:[OTRXMPPRoom collection]];
    }];
    
    //May need to check if the message is unique. Unsure if this is a real problem. Look at XMPPRoomCoreDataStorage.m existsMessage:
    [self insertIncomingMessage:message intoRoom:room];
}
- (void)handleOutgoingMessage:(XMPPMessage *)message room:(XMPPRoom *)room {
}

**focus on handleIncomingMessage:**
// Ignore - we already stored message in handleOutgoingMessage:room:
   
but then:
- (void)handleOutgoingMessage:(XMPPMessage *)message room:(XMPPRoom *)room

is empty?

**Comment by dhomes** [comment] 2016-10-05 12:37
FYI: 
I found the issue to be in OTRXMPPMessageYapStorage handleMessage:stream:incoming

temporarily, i added:

            if([fromStr containsString:@"conference"] || [toStr containsString:@"conference"]) {
                if([xmppMessage isGroupChatMessageWithSubject] == NO) {
                    return;
                }
            }


just above:
            if([[activeThread threadIdentifier] isEqualToString:message.threadId]) {
                message.read = YES;
            }

and problem goes away

This is against an openfire 4.0.1 server

**Comment by dhomes** [comment] 2016-10-05 18:17
@chrisballinger @lucazulian @theSouL @davidchiles 

update: the issue real is in:

OTREncruptionManager's
- (void)otrKit:(OTRKit *)otrKit decodedMessage:(NSString *)decodedMessage wasEncrypted:(BOOL)wasEncrypted tlvs:(NSArray *)tlvs username:(NSString *)username accountName:(NSString *)accountName protocol:(NSString *)protocol tag:(id)tag

------------------------------------------------- 
        [[OTRDatabaseManager sharedInstance].readWriteDatabaseConnection asyncReadWriteWithBlock:^(YapDatabaseReadWriteTransaction *transaction) {
            [originalMessage saveWithTransaction:transaction];
            //Update lastMessageDate for sorting and grouping
            **OTRBuddy *buddy = [OTRBuddy fetchObjectWithUniqueID:originalMessage.buddyUniqueId transaction:transaction];
            buddy.lastMessageDate = originalMessage.date;
            [buddy saveWithTransaction:transaction];**
            
            // Send delivery receipt
            OTRAccount *account = [OTRAccount fetchObjectWithUniqueID:buddy.accountUniqueId transaction:transaction];
            OTRXMPPManager *protocol = (OTRXMPPManager*) [[OTRProtocolManager sharedInstance] protocolForAccount:account];
            [protocol sendDeliveryReceiptForMessage:originalMessage];
        } completionBlock:^{
            [[UIApplication sharedApplication] showLocalNotification:originalMessage];
        }];
    }


if will ALWAYS create a buddy, dont know why decodedMessage is being called for groups, but it goes there.

this fixes it for me (temp fix):
        [[OTRDatabaseManager sharedInstance].readWriteDatabaseConnection asyncReadWriteWithBlock:^(YapDatabaseReadWriteTransaction *transaction) {
            [originalMessage saveWithTransaction:transaction];
            
            OTRBuddy *localbuddy = [OTRBuddy fetchObjectWithUniqueID:originalMessage.buddyUniqueId transaction:transaction];
            
            NSString *username = localbuddy.username;
            NSString *accountId;
            
            if ([username containsString:@"@conference"]) {
                OTRXMPPRoom *room = [OTRXMPPRoom fetchObjectWithUniqueID:originalMessage.buddyUniqueId transaction:transaction];
                room.lastRoomMessageDate = originalMessage.date;
                [room saveWithTransaction:transaction];
                accountId = room.accountUniqueId;
                
            } else {
                
                //Update lastMessageDate for sorting and grouping
                OTRBuddy *buddy = [OTRBuddy fetchObjectWithUniqueID:originalMessage.buddyUniqueId transaction:transaction];
                
                buddy.lastMessageDate = originalMessage.date;
                [buddy saveWithTransaction:transaction];
                accountId = buddy.accountUniqueId;

            }

**Comment by chrisballinger** [comment] 2016-12-15 23:33
Looking into this again now, thanks for the research!

**Comment by chrisballinger** [comment] 2016-12-16 01:19
I think this is fixed in b909943e6f5f9c4b34bb14533b9a5d256e4a8e71

**Closed by chrisballinger** 2016-12-16 01:19 UTC
Labels: Bug
