### ISSUE TITLE
Crashes on Contact Search

### ISSUE THREAD

**Issue by grumpiPad** [ChatSecure/ChatSecure-iOS#479] opened 2016-04-25 17:31 UTC
Reproducability: Every time on iPad Pro and iPhone 6
Annoyance: High.

Whenever the contact list is displayed, the app crashes. Sometimes on opening the search field, sometimes only when selecting a contact from the search results.

Borken by design much?

**Comment by chrisballinger** [comment] 2016-04-25 19:21
Thanks for the report! We are aware of the issue and will be releasing an update addressing this by the end of the week. Looks like a duplicate of this issue: https://github.com/ChatSecure/ChatSecure-iOS/issues/466

**Closed** 2016-04-25 19:22 UTC
