### ISSUE TITLE
Can't register account with ChatSecure.

### ISSUE THREAD

**Issue by gerg5c42g542g2c54g52c** [ChatSecure/ChatSecure-iOS#676] opened 2017-02-04 13:27 UTC
I try to register a new account with creep.im server, but I get an error "Failed to connect to XMPP server. Please check your login credentials and internet connection and try again."

`Domain: com.chatsecure
Code: 1000
UserInfo: {
    NSLocalizedDescription = "Unknown Error";
    OTRXMPPXMLErrorKey = "<iq xmlns=\"jabber:client\" from=\"creep.im\" type=\"error\"><query xmlns=\"jabber:iq:register\"><username>XXXX</username><password>XXXX</password></query><error code=\"405\" type=\"cancel\"><not-allowed xmlns=\"urn:ietf:params:xml:ns:xmpp-stanzas\"/></error></iq>";
}`

**Comment by chrisballinger** [comment] 2017-02-04 18:24
I believe that creep.im requires a captcha, which we don't support at the moment. Otherwise I'm not sure. Does registration work with other apps like Conversations?

**Comment by gerg5c42g542g2c54g52c** [comment] 2017-02-04 20:30
Yes, it does work with Conversations and Converse.js. I'm 100% sure I had to type in captcha when registering with Conversations.

**Comment by chrisballinger** [comment] 2017-02-04 22:56
Okay cool, this is a dupe of #673 

Thanks!

**Closed by chrisballinger** 2017-02-04 22:56 UTC

**Comment by gelft** [comment] 2017-02-17 07:32
> server is not situated in a data center environment and its hardware and Internet channel are not duplicated for a fail-safe operation, hence its services can be inaccessible from time to time due to a network or power outage, a hardware problem, an upgrade or a reboot. Please not rely on Creep.im if the server uptime is crucial to you.
