### ISSUE TITLE
Push Notification Support

### ISSUE THREAD

**Issue by nagpal-saurav** [ChatSecure/ChatSecure-iOS#435] opened 2016-01-26 09:30 UTC
Hi Chris,

Thanks for the such a good open source application. I am facing a problem while integrating the push notification. I have setup all the things on my server for push notification. I think application already have code for push notification support. But it is hitting to knock api and it is not there. Can you help me out?

**Comment by chrisballinger** [comment] 2016-01-27 23:36
Push is not finished yet

**Comment by ashishgupta301** [comment] 2016-02-05 04:50
We have same problem.

We need to decode message which will be send from push notification.

How to We will change it?

**Comment by tmolitor-stud-tu** [comment] 2016-03-12 23:58
@chrisballinger When will push support be finished aproximately?
Many friends of mine have iOS devices and the only xmpp app closely resembling the features of Conversations on android is this one.
But without push support it is rather useless :(

I set a $50 bounty on resolving this (see https://github.com/ChatSecure/ChatSecure-iOS/issues/367)

**Comment by ashishgupta301** [comment] 2016-04-05 05:58
Push for the message is working sometimes in chat secure code.

When we are a terminate application from device yet we get the message like push notification.

We are not uploading any certificates or not register token on our server then how to send it?

**Comment by DreamFlasher** [comment] 2017-01-27 14:36
@chrisballinger @tmolitor-stud-tu Shouldn't this issue be resolved with https://chatsecure.org/blog/chatsecure-v32-push/ ?

**Comment by tmolitor-stud-tu** [comment] 2017-01-27 14:42
@DreamFlasher As far as I know it is not, because the protocol described in the blog post is not compatible with the standard in XEP-0357 (http://xmpp.org/extensions/xep-0357.html) and thus doesn't allow to wake up ChatSecure from Android or Desktop clients (or from iOS clients other than ChatSecure to be precise).

**Comment by chrisballinger** [comment] 2017-01-27 17:35
@tmolitor-stud-tu We do support official XEP-0357 if your server supports it. The protocol described in that post is used underneath the hood for our XEP-0357 support, but was designed to be generic enough to provide the "Knock" workaround for servers that don't yet support XEP-0357.

**Comment by DreamFlasher** [comment] 2017-01-27 17:49
@chrisballinger So this issue should be closed and you deserve your bounty :)

**Closed** 2017-01-27 18:19 UTC
