### ISSUE TITLE
XMPP Chat rooms

### ISSUE THREAD

**Issue by sammcj** [ChatSecure/ChatSecure-iOS#396] opened 2015-09-30 10:52 UTC
Is there any update on when you'll be able to join XMPP chat rooms? They don't even need to be encrypted as that's generally a given in a multi-user room anyway.

This is still the only thing hold back our whole org from using Chat Secure.

**Comment by chrisballinger** [comment] 2015-09-30 20:00
It's on track for v3.2

**Comment by chrisballinger** [comment] 2015-10-02 00:00
Closing as duplicate of #129

**Closed by chrisballinger** 2015-10-02 00:00 UTC
