### ISSUE TITLE
App shows false unread messages in app badge and in app itself

### ISSUE THREAD

**Issue by ronnicek** [ChatSecure/ChatSecure-iOS#608] opened 2016-11-24 08:00 UTC
App shows for example 3 unread messages but I do not have any chats, so I have no idea how to clear them. I still didn't find root cause (most probably push messages). I will try to find out when it happens.. and report more info about it. I know that it was happening also with push client beta (but I cannot find any direct issue with that here).

**Comment by chrisballinger** [comment] 2016-11-24 17:18
The badge count is a computed sum of all unread messages. If you delete those messages it should remove them from the sum, but maybe there are orphaned messages in the db?

**Comment by chrisballinger** [comment] 2016-12-16 21:16
Other people are seeing this issue as well. Do you have MUCs?

**Comment by ronnicek** [comment] 2016-12-16 21:26
No, I don't. But I am not seeing this anymore in few latest beta's :)

**Comment by ronnicek** [comment] 2016-12-18 13:57
Aannnd.. here we are.. Just have it now :-/
![2016-12-18 14-54-02 2663](https://cloud.githubusercontent.com/assets/3885042/21293940/3ba0e2ac-c532-11e6-87f5-4bfe6505d8d2.png)

**Comment by chrisballinger** [comment] 2016-12-19 00:43
> And I found, that it can maybe happen only, when you have account logged from more clients (but it's just guessing now..). But I didnt saw that when I have account connected only thru ChatSecure.

OH! That makes a lot of sense. Here are some thoughts on why this is happening. We have a secondary index to calculate the sum of unread messages. We recently had a migration from a single OTRMessage class to two OTRIncomingMessage and OTROutgoingMessage classes which might have messed up that logic. Based on what you said, we are possibly counting incoming message carbons as "unread" messages, with no way to ever read them.. because reading messages probably only applies to incoming messages from other contacts.

**Comment by ge0rg** [comment] 2017-01-03 10:48
Receiving an "outgoing" carbon for an existing chat doesn't increase the "unread" counter. Mine is at 73 now, I'm logged into two accounts with beta 57, and no way to reset :(

**Comment by ge0rg** [comment] 2017-01-03 14:34
Update: the counter is increased on receiving "incoming" carbons. These also don't make the sender appear in "Chats", which is probably a bug of its own.

I can manually start a chat with the sender to reduce the "unread" counter. Obviously I need to know all the senders to bring it down to 0.

**Comment by chrisballinger** [comment] 2017-01-03 19:44
>  These also don't make the sender appear in "Chats", which is probably a bug of its own.

I did some unrelated refactoring last week that might fix that, which should allow you to at least see which conversation is now considered unread, and show all the unread threads in the conversation list.

**Comment by ge0rg** [comment] 2017-01-04 08:31
Updated to beta 58, opened the app from TestFlight, and the counter was vanished at first.

Unfortunately, the app didn't connect to the server (was showing "Connecting..." all the time), so I killed it and restarted. Now I'm back at unread=72, like before. I think there are some more chats in the Chats view now than with the previous version, but none of them has unread messages (none is bold, and opening all of them didn't affect the counter).

**Comment by chrisballinger** [comment] 2017-01-04 18:11
Ah, so we are only bolding the conversation if the last message associated with that conversation (sent or received) is considered "read", and it's always considered read if it's an outgoing message. 

Fixing this will be.. interesting.. because of how we've structured the database.

**Comment by chrisballinger** [comment] 2017-01-04 19:57
Fixed in 92442c151c9c413de8e91c510937c3a2addb643e

**Comment by ge0rg** [comment] 2017-01-05 20:21
Any chance for a new beta release, then?

**Comment by chrisballinger** [comment] 2017-01-05 23:12
I almost released one last night but it had a crash on launch bug on my
device. Then today my computer's charging port didn't work so hopefully if
I can get that fixed this afternoon I'll be able to put something out
tonight.

**Comment by ge0rg** [comment] 2017-01-06 08:56
Beta 60 once again doesn't complete "connecting" to the server sometimes.

Also, now I have one bold JID in the "Chats (29)" tab, and the last message in that chat is from me. Opening and closing the chat tab does not remove the bold marker, and does not reduce the number of unread messages.

**Comment by chrisballinger** [comment] 2017-01-06 17:42
I've seen this connection issue intermittently for a long time and I don't think it's necessarily new, but maybe exacerbated by our changes.

When you see the "connecting" issue, can you try to see if the app is hitting a db pause by sending a message or hitting (i)?

The unread issue is curious and I'm not sure why it isn't fixed, but at least the issue is now just in the code to mark messages as read.

**Comment by ge0rg** [comment] 2017-01-06 19:26
I'm pretty sure it freezed when I pressed (i) on a contact in the "Connecting" state.

Can't you mark all messages from the JID as read when opening/closing the tab?

**Comment by chrisballinger** [comment] 2017-01-06 20:28
> I'm pretty sure it freezed when I pressed (i) on a contact in the "Connecting" state.

Ok good this mean it's related to our database issue. We talked to the author of YapDatabase today and think we have narrowed down a few possible causes that we are investigating.

> Can't you mark all messages from the JID as read when opening/closing the tab?

Technically this is what we already do... but we must have broken it somehow. :)

**Comment by ge0rg** [comment] 2017-01-07 09:17
Wow, something happened and now the counter is down to 0 in beta 61. It started out with (30) and two bold chats, I opened both, and the counter didn't reset immediately, but after some seconds it was gone.

**Comment by chrisballinger** [comment] 2017-01-07 17:51
Aw yeah! The database goes through a lot of churn on launch that can delay that from updating immediately in the UI because we do it asynchronously. However, we made a huge improvement to the database churn in beta 61 by moving a lot of ephemeral buddy properties out of the database and into an in-memory cache, so we are crossing our fingers that this helps mitigate the long UI pauses as well.

**Closed by chrisballinger** 2017-01-07 17:51 UTC
Labels: Bug, UI / UX
