### ISSUE TITLE
Frequent UI freezes / deadlocks

### ISSUE THREAD

**Issue by stigger** [ChatSecure/ChatSecure-iOS#552] opened 2016-08-20 19:10 UTC
Application freezes quite often without any feedback. Sometimes it unfreezes after 10-30 seconds, sometimes it simply crashes after that.

**Comment by chrisballinger** [comment] 2016-08-21 02:13
Do you have a large number of contacts and/or messages?

**Comment by stigger** [comment] 2016-08-21 02:16
Nope, very little of both. Most often the lockups happen on opening chat message, connect/disconnect, sending a message. On iPhone 6 this happens now so often, but on iPhone 5 it's much more often.

**Comment by chrisballinger** [comment] 2016-08-21 02:23
I've seen occasional UI hangs but usually just when entering a conversation, and never long enough to cause the app to quit (on a 6S). We definitely could do a better job of fetching a smaller subset of messages when entering a conversation, and try to eliminate more areas where we might block the main thread.

**Comment by stigger** [comment] 2016-08-21 02:25
Just remembered one more case when it hangs regularly: on a cold start it freezes for a significant time with an empty UITableView.

**Comment by chrisballinger** [comment] 2016-08-21 02:27
On the initial screen or when entering conversation?

**Comment by stigger** [comment] 2016-08-21 02:28
Initial screen.

**Comment by chrisballinger** [comment] 2016-10-24 19:45
This is happening more often for me, and we are investigating.

**Comment by vanitasvitae** [comment] 2016-11-04 17:05
Just want to let you know, that my brother had the same issues on his iPhone 6+. That made him quit using ChatSecure, so I am glad this is on the radar and hopefully gets fixed, so I can convince him to give it another try.

**Comment by chrisballinger** [comment] 2016-11-04 18:07
It seems to happen more if you have more accounts, contacts, and messages in the database. I haven't been able to narrow it down but it primarily occurs on first launch on the conversations screen and when entering a conversation for the first time. I am wondering if it has anything to do with receiving a push in the background, or fetching background updates, because I haven't ever been able to reproduce it when running from the debugger.

The OS doesn't count it as a crash either, so we don't get any reports to help us debug... very frustrating.

**Comment by vanitasvitae** [comment] 2016-11-04 18:09
In case of my brother, he only had 2 contacts on one account and it lagged out right from the beginning, so I doubt it has to do with databases or much data.

**Comment by stigger** [comment] 2016-11-04 18:14
If I remember correctly, my attempts to quickly profile it showed two problems:
1) YapDatabase was being quite CPU-intensive
2) ChatSecure does queries to the YapDatabase on the UI thread, which causes the lags.

I don't know all the rationale behind the current approach, but I'd ditch YapDatabase and rely solely on the security mechanisms provided by iOS. They are effective and secure enough (most of the time).

**Comment by chrisballinger** [comment] 2016-11-04 18:18
We definitely could reduce queries on the main thread, but sometimes it is unavoidable. My hunch is that there is a nested transaction somewhere, which could definitely cause this issue, but I'm confused as to why it's non-deterministic and doesn't appear when run in the debugger.

YapDB is pretty well integrated in the entire app, so there's a 0% chance we will be moving to anything else any time soon. The SQLCipher extension adds about a 10% overhead, but shouldn't ever cause a deadlock.

This issue is definitely a blocker for the 4.0 release, so we are definitely working on it.

**Comment by chrisballinger** [comment] 2016-12-15 23:38
I've done as much as I can to improve this for 4.0 but still haven't gotten to the root of the cause. I'm going to bump this to the 4.1 milestone so we can at least get a release out the door.

**Comment by chrisballinger** [comment] 2017-01-05 01:55
Still blocking after a big refactor. I think we aren't the only one with these issues: https://github.com/yapstudios/YapDatabase/issues/197

**Comment by chrisballinger** [comment] 2017-01-09 22:22
I think it's fixed in the latest beta with our addition of OTRBuddyCache.

**Closed by chrisballinger** 2017-01-09 22:22 UTC
Labels: Bug, UI / UX
