### ISSUE TITLE
All contacts offline

### ISSUE THREAD

**Issue by Willpower77** [ChatSecure/ChatSecure-iOS#674] opened 2017-01-31 14:31 UTC
I have the latest version ChatSecure, and I have all the contacts and offline contacts that are online.

**Comment by chrisballinger** [comment] 2017-01-31 17:25
Thanks for the feedback! Closing this as a duplicate of https://github.com/ChatSecure/ChatSecure-iOS/issues/668

**Closed by chrisballinger** 2017-01-31 17:25 UTC
