### ISSUE TITLE
App created password automatically, how can I change or use it?

### ISSUE THREAD

**Issue by erikb85** [ChatSecure/ChatSecure-iOS#532] opened 2016-07-07 18:58 UTC
I want to login to the same account the app created from other devices, be able to change the password, add my github account etc. But the app just created a password for me, which I don't know and don't seem to be able to change. How to continue?

**Comment by chrisballinger** [comment] 2016-07-07 20:07
Somewhat dupe of #529. This is fixed in the latest TestFlight beta which allows you to view your password. However it doesn't yet allow you to change it.

**Closed by chrisballinger** 2016-07-07 20:07 UTC

**Comment by erikb85** [comment] 2016-07-08 10:44
If possible please add that to the FAQs. It's quite relevant as a user. ;)
